# Generated by Django 5.1.3 on 2025-01-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fi_system_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='url_address',
        ),
        migrations.AddField(
            model_name='agent',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='agent',
            name='host',
            field=models.CharField(default='localhost', max_length=200),
        ),
        migrations.AddField(
            model_name='agent',
            name='port',
            field=models.CharField(default='80', max_length=8),
        ),
        migrations.AddField(
            model_name='agent',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=100),
        ),
        migrations.AddField(
            model_name='fuzzingtarget',
            name='last_status',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='fuzzingtarget',
            name='target_name',
            field=models.CharField(default='No target name', max_length=200),
        ),
    ]
